### ISSUE TITLE
Command npm install doenst work

### ISSUE THREAD

**Issue by Kuhrupt** [Bundesdruckerei-GmbH/Gematik-IDP#10]
package.json just got created if npm init -y is also executed, but the package.json doestn include a build variable:
{
  "name": "gematik-idp",
  "version": "1.0.0",
  "description": "[IDP plugin](https://www.keycloak.org/docs/latest/server_development/index.html#identity-brokering-apis) to integrate the gematik central-IDP with the gematik Authenticator application. Allows a user to log in with his HBA (Heil-Berufs-Ausweis) card, supplying HBA and SMCB (Elektronischer Praxis-/Institutionsausweis) card information. Additionally, HBA- and SMCB-specific IDP mappers are provided.",
  "main": "index.js",
  "directories": {
    "doc": "docs"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}

so nothing happens to the command npm run build:gematik-idp.

anybody knows how i can fix it? already tried to update npm and maven. dont know any further steps i can take. thank your very much for your help!

**Comment by florianschiller** [comment]
Hello @Kuhrupt ,

Thanks for the hint. You don't have to run npm so you can just skip that step. 
The documentation seems to be outdated. I'll correct it later today.

Best regards,
Florian
