### ISSUE TITLE
Authentisierung mittels HBA konfigurierbar machen

### ISSUE THREAD

**Issue by Rafael81B** [Bundesdruckerei-GmbH/Gematik-IDP#5]
In unserem Projekt gibt es die fachliche Anforderung die Authentisierung des Benutzers lediglich mittels SMC-B durchzuführen. Daher wird eine Möglichkeit benötigt die Authentisierung mittels HBA zu deaktivieren. Eine mögliche Lösung schlagen wir in https://github.com/Bundesdruckerei-GmbH/Gematik-IDP/pull/4 vor.

**Comment by simse07** [comment]
Hi @Rafael81B 

vielen Dank, auch für den Lösungsvorschlag.
Wir werden uns das ansehen.

**Comment by simse07** [comment]
Hi @Rafael81B 

wir haben uns deinen Vorschlag angesehen und würden diesen gerne dynamischer gestalten.
Anstatt nur die HBA zu deaktivieren, würde wir vorschlagen, alle 3 Möglichkeiten anzubieten:

1. Authentisierung mit HBA und SMCB
2. Authentisierung mit HBA
3. Authentisierung mit SMCB

Wir werden das Feature nun in unserem Projekt planen und implementieren.
Ich gebe dir Bescheid, sobald wir dazu Neuigkeiten haben.

**Comment by Rafael81B** [comment]
Vielen Dank für die Rückmeldung. Wir freuen uns, dass das Feature geplant und umgesetzt wird.

**Comment by florianschiller** [comment]
Das Feature, einzeln SMC-B oder einzeln HBA abzufragen, wurde in der Zwischenzeit zum Plugin hinzugefügt. Das Feature funktioniert aber nur mit einem Authenticator in Version 4.6.0 oder höher.
