### ISSUE TITLE
Telematik-ID aus SMC-B kann nicht auf User-Attribut gemappt werden

### ISSUE THREAD

**Issue by Rafael81B** [Bundesdruckerei-GmbH/Gematik-IDP#6]
Wir haben einen Mapper vom Typ "Gematik SMCB Claim Attribut" für den Gematik Claim TELEMATIK_ID angelegt. Der Mapper wird zwar aufgerufen, allerdings wird das Attribut nicht ins Benutzerprofil übernommen. 

Eine Analyse hat ergeben, dass das Mapper-Modell das Attribut "claimAttribute" nicht enthält. 

Der Fehler wurde im Zusammenspiel mit KC 21.1.1 beobachtet

**Comment by simse07** [comment]
Hi @Rafael81B,

vielen Dank, wir werden uns das anschauen.

**Comment by simse07** [comment]
Hi @Rafael81B ,

leider konnte ich den Bug in Keycloak 21.1.2 nicht reproduzieren.
Wir mussten auch das neue Admin-UI anpassen, um den Gematik-IDP hinzuzufügen. Wir arbeiten daran, wie wir diese Änderungen bereitstellen können.

Könntest du noch weitere Informationen bereitstellen, u.a. Screenshots von der Mapper Config, dem beobachteten Verhalten usw.?

**Comment by Rafael81B** [comment]
Hallo @simse07,

der im Ticket beschriebene Issue wird mit Keycloak 21.1.1 beobachtet. Die Mapper-Konfiguration ist wie folgt:
![image](https://github.com/Bundesdruckerei-GmbH/Gematik-IDP/assets/109286098/c9f5ca89-c1d6-4c92-a432-e789241fec81)

In Keycloak 21.1.2 tritt das beschriebene Problem nicht mehr auf, ich werde das Ticket daher schließen.
